export {
  QUOTE_DOCUMENT_CONTENT_VERSION,
  QUOTE_DOCUMENT_REGION_ID_PATTERN,
  buildQuoteDocumentContent,
  buildQuoteDocumentRegionId,
  createEmptyQuoteDocumentContent,
  createQuoteDocumentRegion,
  parseQuoteDocumentRegionId,
  quoteDocumentContentRegionSchema,
  quoteDocumentContentSchema,
  quoteDocumentRegionIdSchema,
  quoteDocumentRegionSchema,
  quoteDocumentRegionTargetSchema,
  quoteDocumentRegionsSchema,
  slugifyQuoteDocumentRegionToken,
  type QuoteDocumentContent,
  type QuoteDocumentContentRegion,
  type QuoteDocumentContentSeedInput,
  type QuoteDocumentRegion,
  type QuoteDocumentRegionId,
  type QuoteDocumentRegionTarget,
  type QuoteDocumentRegions,
} from "@open-harness/quote-documents/lib/documents/quote/document-content";
