export {
  QuoteDocument,
  generateQuotePDF,
} from "./lib/documents/quote/generator";
export {
  buildQuoteJsonRenderSpec,
  renderQuotePdfWithJsonRender,
  QUOTE_JSON_RENDER_SECTION_ORDER,
  type QuoteJsonRenderElement,
  type QuoteJsonRenderElementType,
  type QuoteJsonRenderSectionKey,
  type QuoteJsonRenderSpec,
} from "./lib/documents/quote/json-render";
export {
  quoteDataSchema,
  type QuoteData,
} from "./lib/documents/quote/schema";
export {
  quoteRichContentBlockSchema,
  quoteRichContentBlocksSchema,
  quoteRichDividerBlockSchema,
  quoteRichHeadingBlockSchema,
  quoteRichImageBlockSchema,
  quoteRichListBlockSchema,
  quoteRichParagraphBlockSchema,
  quoteRichQuoteBlockSchema,
  quoteRichSpacerBlockSchema,
  quoteRichStatsBlockSchema,
  quoteRichStatItemSchema,
  quoteRichTableBlockSchema,
  quoteRichTableColumnSchema,
  quoteRichTextAlignSchema,
  type QuoteRichContentBlock,
  type QuoteRichContentBlocks,
} from "./lib/documents/quote/rich-content";
export {
  QUOTE_DOCUMENT_CONTENT_VERSION,
  QUOTE_DOCUMENT_REGION_ID_PATTERN,
  QUOTE_DOCUMENT_REGION_TARGETS,
  buildQuoteDocumentContent,
  buildQuoteDocumentRegionId,
  createEmptyQuoteDocumentContent,
  parseQuoteDocumentRegionId,
  quoteDocumentContentRegionSchema,
  quoteDocumentContentSchema,
  quoteDocumentRegionIdSchema,
  quoteDocumentRegionScopeSchema,
  quoteDocumentRegionTargetSchema,
  quoteDocumentRegionsSchema,
  slugifyQuoteDocumentRegionToken,
  type QuoteDocumentContent,
  type QuoteDocumentContentRegion,
  type QuoteDocumentRegionId,
  type QuoteDocumentRegionScope,
  type QuoteDocumentRegionTarget,
  type QuoteDocumentRegions,
} from "./lib/documents/quote/document-content";
export {
  QUOTE_DOCUMENT_CATALOG_VERSION,
  QUOTE_DOCUMENT_DEFAULT_ENABLED_SECTIONS,
  QUOTE_DOCUMENT_SECTION_KEYS,
  QUOTE_DOCUMENT_SECTION_VARIANTS,
  QUOTE_DOCUMENT_SERVICE_LAYOUTS,
  createDefaultQuoteDocumentPlan,
  getQuoteDocumentSectionSelection,
  isQuoteDocumentSectionEnabled,
  quoteDocumentPlanSchema,
  quoteDocumentSectionKeySchema,
  quoteDocumentSectionSelectionSchema,
  quoteDocumentSectionVariantSchema,
  quoteDocumentServiceLayoutSchema,
  type QuoteDocumentPlan,
  type QuoteDocumentSectionKey,
  type QuoteDocumentSectionSelection,
  type QuoteDocumentSectionVariant,
  type QuoteDocumentServiceLayout,
} from "./lib/documents/quote/document-plan";
export {
  QUOTE_DOCUMENT_LEGACY_FLAG_KEYS,
  QUOTE_DOCUMENT_SECTION_GROUPS,
  getQuoteDocumentSectionCatalogEntry,
  quoteDocumentSectionCatalog,
  quoteDocumentSectionCatalogEntries,
  type QuoteDocumentLegacyFlagKey,
  type QuoteDocumentSectionCatalogEntry,
  type QuoteDocumentSectionGroup,
} from "./lib/documents/quote/section-catalog";
export {
  applyQuoteDocumentComposition,
  resolveQuoteDocumentRenderInput,
  type QuoteDocumentCompositionState,
  type QuoteDocumentRenderInput,
} from "./lib/documents/quote/composition";
export {
  buildLegacyQuoteRegistryElements,
  createLegacyQuotePdfSectionRegistry,
  renderEnabledLegacyQuoteSections,
  renderLegacyQuoteSection,
  type LegacyQuoteRegistryElementDefinition,
  type LegacyQuoteRegistryRenderArgs,
} from "./lib/documents/quote/legacy-section-registry";
export {
  createLegacyQuoteSectionRenderContext,
  getEnabledLegacyQuoteSectionKeys,
  resolveEnabledLegacyQuoteSections,
  resolveLegacyQuoteSection,
  LEGACY_QUOTE_SECTION_ORDER,
  LEGACY_QUOTE_SECTION_TYPES,
  type CreateLegacyQuoteSectionRenderContextOptions,
  type LegacyQuoteRenderAssets,
  type LegacyQuoteResolvedSection,
  type LegacyQuoteSectionAdapter,
  type LegacyQuoteSectionKey,
  type LegacyQuoteSectionPropsMap,
  type LegacyQuoteSectionRegistryType,
  type LegacyQuoteSectionRenderContext,
} from "./lib/documents/quote/legacy-section-adapters";
export { QuoteRichContentRenderer } from "./lib/documents/quote/rich-content-renderer";
